#!/bin/bash

FOLDER=`dirname "$BASH_SOURCE"`
LOCK="$FOLDER/lock.png"
TEXT="$FOLDER/text.png"
OUTPUT_IMAGE="/tmp/i3lock.png"

#Take screenshot:
scrot $OUTPUT_IMAGE

# Crop the screenshot to primary display
convert $OUTPUT_IMAGE -crop 1366x768+0+0\! \
  -filter Gaussian -resize 20% -define filter:sigma=1.5 -resize 500.5% \
  $LOCK -gravity center -composite \
  $TEXT -geometry +0+150 -composite $OUTPUT_IMAGE

# Enlarge the image to cover multi-monitor
convert $OUTPUT_IMAGE -background black -extent 2806x900 -gravity NorthWest $OUTPUT_IMAGE

#Lock the screen:
i3lock -i $OUTPUT_IMAGE -t

#Remove the generated image:
rm $OUTPUT_IMAGE
